### ISSUE TITLE
Header & Footer Color Choices

### ISSUE THREAD

**Issue by ta0a2000t** [ta0a2000t/casuafolio#12]
- In `stylingConstants.js`, let the user choose a color for the footer and header bars.
  - Only the color should be selectable, not the opacity.
    - This is to maintain a visually appealing website on mobile devices with small screens.

Example in JavaScript:
```javascript

/*
Color Options:
  - Default: 282c34
  - Red: FF0000
  - Blue: 0000FF
  - Green: 008000
  ...etc
*/
export const HEADER_FOOTER_COLOR = "282c34";  // Default
```
Notes: 
- please keep default color as `#282c34`
- to keep the opacity 0.7 (as it is now, append "b7" to the end of the color). For example: #282c34b7, which is # + 282c34 + b7
- stylingConstants.js should have no code! all coding outside. you just get the color from stylingConstants.js.

Add instructions in the comments. instructions clear enough for non-programmers to understand.

**Comment by parag477** [comment]
I want to work on this issue. Can you please assign me this issue?

**Comment by ta0a2000t** [comment]
[corners2wall](https://github.com/corners2wall) already done most of it. See https://github.com/ta0a2000t/casuafolio/issues/17 it is very similar, but much more complicated :)
