### ISSUE TITLE
XML Sitemap (better Google search ranking)

### ISSUE THREAD

**Issue by ta0a2000t** [ta0a2000t/casuafolio#14]
Include an XML sitemap to help with SEO.

**Comment by parag477** [comment]
I want to work on this issue. Can you please assign me this issue.

**Comment by ta0a2000t** [comment]
Yes! Assigned.

**Comment by parag477** [comment]
Hey I have done the task. Please check it and merge my pull request.

**Comment by ta0a2000t** [comment]
closed with https://github.com/ta0a2000t/casuafolio/pull/21
